# Generated by Django 4.0.2 on 2022-03-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="text",
        ),
    ]
