# Generated by Django 4.0.2 on 2022-03-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_blog_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
