# Generated by Django 4.0.2 on 2022-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="Cri's Blog 2.0!", max_length=50),
        ),
    ]
