# Generated by Django 4.0.2 on 2022-02-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ManyToManyField(default="New", to="blog.Category"),
        ),
    ]
